name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: xlui/action-maven-cli/jdk11@master
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml